apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod-app
  namespace: hotrod
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: hotrod-app
  template:
    metadata:
      labels:
        app: hotrod-app
    spec:
      containers:
      - name: hotrod
        image: jaegertracing/example-hotrod:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 8083
          name: svc-metrics
