apiVersion: v1
kind: Service
metadata:
  name: hotrod-metrics
  namespace: hotrod
  labels:
    app: hotrod-metrics
spec:
  selector:
    app: hotrod-app
  ports:
  - port: 8083
    targetPort: 8083
    name: svc-metrics
