apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hotrod-servicemonitor
  labels:
    prometheus: kube-prometheus
    release: prometheus
    role: service-monitors
spec:
  selector:
    matchLabels:
      app: hotrod-metrics
  endpoints:
  - port: svc-metrics
    interval: 15s